version: '3.8'

services:
  python-app:
    build: .
    container_name: python_app_container
    environment:
      - APPARTMENT_COLUMN_NAME=14
      - ADDRESS_COLUMN_NAME=13
      - DB_NAME=db.csv
      - INPUT_FILE_NAME=input.csv
      - TABLE_NAME=table1

    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./db:/app/db
      - ./log:/app/log
    working_dir: /app
    command: ["python3", "scripts/main.py"]
